apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-site-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-site-ui
  template:
    metadata:
      labels:
        app: blog-site-ui
    spec:
      containers:
        - name: blog-site-ui
          image: piyushdubey1994/blog-site-ui:tagversion
          ports:
            - containerPort: 80
          volumeMounts:
            - name: react-app-volume
              mountPath: /usr/share/nginx/html  # Ensure React app is mounted correctly
      volumes:
        - name: react-app-volume
          configMap:
            name: react-app-configmap  # Use ConfigMap to load your build files if needed
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: blog-site-ui-service
spec:
  type: LoadBalancer  # Use NodePort or LoadBalancer depending on your setup
  selector:
    app: blog-site-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#  loadBalancerIP: <YOUR_STATIC_IP>  # Optional: Assign a static IP if needed

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: blog-site-ui-ingress
#spec:
#  rules:
##    - host:
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: blog-site-ui-service
#                port:
#                  number: 80
