apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-site-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-site-ui
  template:
    metadata:
      labels:
        app: blog-site-ui
    spec:
      containers:
        - name: blog-site-ui
          image: piyushdubey1994/blog-site-ui:tagversion
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: blog-site-ui-service
spec:
  type: LoadBalancer
  selector:
    app: blog-site-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
